### ISSUE TITLE
How to uninstall the application which installed by makefile

### ISSUE THREAD

**Issue by 8ar10der** [45Drives/cockpit-file-sharing#102]
Hi, I am ready to remove the application. I installed by the `make install`.

I read the makefile looks like all the files are copied to the `/usr/share/cockpit/file-sharing/` and no more.

So, I just need to rm this dictionary and restart the cockpit service, right?

I need to confirm this with you. Thanks.

**Comment by bkelly16** [comment]
Correct.

```
rm -rf /usr/share/cockpit/file-sharing/
systemctl restart cockpit.socket
```

**Comment by 8ar10der** [comment]
> Correct.
> 
> ```
> rm -rf /usr/share/cockpit/file-sharing/
> systemctl restart cockpit.socket
> ```
> 

Thanks a lot!
