### ISSUE TITLE
Quota updating with SMB shares in file-sharing 2.4.0 

### ISSUE THREAD

**Issue by Hutch-45D** [45Drives/cockpit-file-sharing#12]
After the newest File-sharing update that added Ceph Quotes for SMB shares, the quota is set on creation but when you edit the share and change the quota it does not update.

Changing the quota and saving it does not display the new set quota in "df" or show in the ceph dashboard or on the client systems that had the share mapped.

Manually updating the quota in the ceph dashboard did reflect the new set quota but file-sharing was not able to push the newly updated quota  to ceph

**Comment by markdhooper** [comment]
bump (to test slack bot)

**Comment by markdhooper** [comment]
bump

**Comment by bkelly16** [comment]
Understood.
ill update here when we've got a release up for testing

**Comment by bkelly16** [comment]
fixed in v2.4.1-1
