### ISSUE TITLE
Cannot set user or group in Samba share GUI

### ISSUE THREAD

**Issue by rhclayto** [45Drives/cockpit-file-sharing#125]
## Bug Info

**Describe the bug**
The select lists for 'valid users' & 'valid groups' are missing when I try to add a Samba share.

**To Reproduce**
1. Click on the 'add share' plus button on the share GUI, as explain at https://knowledgebase.45drives.com/kb/kb450281-managing-smb-in-houston-ui/
2. Observe no select lists for user or group.

**Expected behavior**
Able to add users & groups in the GUI.

**Screenshots**
![sambaShareNoUsersGroups](https://github.com/user-attachments/assets/023ce7e6-bb14-4a51-975b-6da4aaf23d6d)

**Console Output**
Not sure if related, but:
- Firefox (latest):
```
TypeError: can't access property "rangeCount", selection is null4 [contextmenuhlpr.js:8:9](moz-extension://723694ba-b09d-403f-bcfc-977a03844a1c/contextmenuhlpr.js)
    dealWithSelection moz-extension://723694ba-b09d-403f-bcfc-977a03844a1c/contextmenuhlpr.js:8
    <anonymous> moz-extension://723694ba-b09d-403f-bcfc-977a03844a1c/contextmenuhlpr.js:85
    (Async: EventListener.handleEvent)
    vis moz-extension://723694ba-b09d-403f-bcfc-977a03844a1c/contextmenuhlpr.js:76
    <anonymous> moz-extension://723694ba-b09d-403f-bcfc-977a03844a1c/contextmenuhlpr.js:81
    #injectIntoIsolatedWorld resource://gre/modules/ExtensionContent.sys.mjs:687
    inject resource://gre/modules/ExtensionContent.sys.mjs:672
    injectInto resource://gre/modules/ExtensionContent.sys.mjs:536
    loadContentScript resource://gre/modules/ExtensionProcessScript.sys.mjs:420
```

## Client Side

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 134.0b7

## Server Side
 - OS: Debian 12
 - Cockpit Version: cockpit-file-sharing/now 4.2.8-1focal, cockpit/stable,now 287.1-0+deb12u3

**Comment by mtisza** [comment]
The README was updated to show the this was removed/changed in v4.  See https://github.com/45Drives/cockpit-file-sharing?tab=readme-ov-file#fieldssettings
The KB article should be updated to show the correct way to handle valid users and groups in v4. (manually setting "valid users = ...." in advanced settings).
Curious why this was changed.  Seems like a step backwards.

**Comment by rhclayto** [comment]
Thanks for the pointer. It does seem like a weird setting to remove from the GUI. Anyway, I thought a GUI would be nice, but I find plain old smb.conf nicer, so I'm running with that.

**Comment by Crypto-Spartan** [comment]
Is there a guide/documentation for how to do this? I haven't been able to find anything so far

**Comment by 0xskynet** [comment]
> The README was updated to show the this was removed/changed in v4. See https://github.com/45Drives/cockpit-file-sharing?tab=readme-ov-file#fieldssettings The KB article should be updated to show the correct way to handle valid users and groups in v4. (manually setting "valid users = ...." in advanced settings). Curious why this was changed. Seems like a step backwards.

@mtisza  did you figure out how to restrict the samba share to specific users with "advanced settings"? What's the syntax?

**Comment by mtisza** [comment]
@0xskynet manually setting "valid users = ...." in advanced settings worked for me.

**Comment by 0xskynet** [comment]
> [@0xskynet](https://github.com/0xskynet) manually setting "valid users = ...." in advanced settings worked for me.

@mtisza Thanks for the reply. so like `valid users = user1 user2 user3` ? How do you do with groups? `valid groups = group1 group2` ?
