### ISSUE TITLE
Adding KB articles about SMB/NFS to Help button in File Sharing Module

### ISSUE THREAD

**Issue by bailey-97** [45Drives/cockpit-file-sharing#13]
Currently in the file sharing module the help button just lists the default Red Hat Web Console Article:

![file-sharing-help](https://user-images.githubusercontent.com/88982700/134566257-12f1f0d0-ac4d-44b1-936d-9d9213f37676.PNG)

Would it be possible to update the manifest.json for the module to include some of the KB articles for managing SMB/NFS etc so it appears like this, and links directly to our KB articles:

![file-sharing-help-2](https://user-images.githubusercontent.com/88982700/134566369-67acb928-7c94-4c48-a75d-67df6369f429.PNG)

**Comment by bkelly16** [comment]
yes will do, we will include this when we push a release for #12

**Comment by bkelly16** [comment]
@bailey-97  can you give me the links you want included ?

**Comment by bailey-97** [comment]
my bad,

it would be good to have these two:

https://knowledgebase.45drives.com/kb/kb450281-managing-smb-in-houston-ui/

https://knowledgebase.45drives.com/kb/kb450282-managing-nfs-in-houston-ui/

**Comment by bkelly16** [comment]
Closed with release v2.4.1-2
