### ISSUE TITLE
Cockpit-File-Sharing2.4.0, Not deleting shares 

### ISSUE THREAD

**Issue by Hutch-45D** [45Drives/cockpit-file-sharing#15]
After creating a share in file sharing if you attempt to delete or remove the share it does not. you can see a wheel spinning in the background of the tab after pressing delete but nothing happens

this has been tested on Ubuntu 20.04 and Rocky8.4. the workaround, for now, is to use "net conf delshare share" and then manually deleting the directory in navigator or the terminal

**Comment by Hutch-45D** [comment]
Also cant assign labels to the issue. should be a bug

**Comment by bkelly16** [comment]
fixed in release 2.4.1-1
