### ISSUE TITLE
Alma Linux cockpit error "cannot update repo '45drives_stable': repomd.xml"  after install

### ISSUE THREAD

**Issue by bobbluesystems** [45Drives/cockpit-file-sharing#16]
First I would like to thank all the contributors to this project for the great tool that has been shared with the community.
Second ....
Using a fresh headless install of Alma Linux 8.4 with samba installed and running...
Followed install instructions below...
"
$ curl -o /etc/yum.repos.d/45drives.repo http://images.45drives.com/repo/centos/45drives-centos.repo
$ dnf clean all && dnf makecache
$ dnf install cockpit-file-sharing
"
Result was a nicely working Cockpit Samba config tool that is a great addition to Samba command line configuration tools.
I especially like the Samba user configure tool included.
But....Now cockpit reports the following error message under "Software Updates "
"cannot update repo '45drives_stable': repomd.xml GPG signature verification error: Bad GPG signature"
Is this a security signature that is now out of date, missing or in error? If so how do I correct this error.
Any suggestions will be greatly appreciated.
Thanks

**Comment by dawsondellavalle** [comment]
Hi there,

That repository is no longer maintained and we must have missed the instructions for this module. You can visit https://repo.45drives.com/setup.html to update the repo file installed on your system which should setup the latest versions of our packages.

**Comment by bobbluesystems** [comment]
Worked perfect and resolved the issue.
Thank you again for your contribution to the community.
