### ISSUE TITLE
[feature request] fedora support for cockpit-file-sharing plugin

### ISSUE THREAD

**Issue by routerino** [45Drives/cockpit-file-sharing#19]
It would be nice to be able to use these plugins for fedora, seeing as centos/rocky does not have btrfs support (yet). Given that fedora is upstream of centos, *hopefully* that wouldn't involve a large degree of work.

Attempting to add the repository and install `cockpit-file-sharing` gets dependency errors upon installation.

Also tried installing the dependencies manually then installing the rpm directly, no go:
![image](https://user-images.githubusercontent.com/45954722/137577144-927d37a7-e518-413a-9295-edbff7c5667a.png)

Building from source seems to be working fine *so* far.

**Comment by player8472** [comment]
Same here.

I don't like building from source since I always forget to take care of updating it (and too lazy to build automation myself...)

**Comment by q2dg** [comment]
Maybe here there is the solution: https://www.phoronix.com/scan.php?page=news_item&px=Fedora-36-Cockpit-Sharing

**Comment by sirweazel** [comment]
Someone can probably closet this, as i think its already in the the fedora repos. I just installed it in Fedora 35 server with a simple DNF install.
