### ISSUE TITLE
scrolling samba tab

### ISSUE THREAD

**Issue by mth778472** [45Drives/cockpit-file-sharing#22]
How to get vertical scrolling working on samba tab? If you have a lot of shares you are not able to scroll down ... doesn't work on Win10 with Edge, Firefox and even Chrome ...

**Comment by bkelly16** [comment]
Can you provide the version of cockpit you are using ? Can confirm that scrolling works as intended on v250.

**Comment by mth778472** [comment]
Hi bkelly16, thank you very much for your prompt reply ... and you also gave the answer ;-) I've had version 1.0 installed, after upgrading everything works perfectly!
