### ISSUE TITLE
cannot add samba share on armbian 11 

### ISSUE THREAD

**Issue by Omoinemie** [45Drives/cockpit-file-sharing#25]
ver: 2.4.1
problem: cannot add smb share
os: arm64 debian 11
![Snipaste_2021-12-10_23-06-45](https://user-images.githubusercontent.com/31991443/145596030-53ba8b89-e8f2-48af-9c0e-2ce99530ea50.png)

**Comment by joshuaboud** [comment]
Should be fixed in v2.4.2, commit b489462136cff5f150d1fb10b6f0c7a535ddb901

**Comment by joshuaboud** [comment]
can you also check if the package `xattr` is installed by running `getfattr`?

**Comment by Omoinemie** [comment]
line 1625 is the same!

**Comment by joshuaboud** [comment]
Apologies, the same issue is there twice. I fixed it on line 1613 but missed it on 1625. Commit cad6d3144991fd98d47796f9d4c4701919c7aa5f should fix this, included in release 2.4.3.

**Comment by Omoinemie** [comment]
thanks, can you add the ftp/sftp and webdav manager In the future

**Comment by joshuaboud** [comment]
We will look into adding SFTP in the future, but it is unlikely that we'd add FTP as it is very insecure. WebDAV is also unlikely as it requires setting up and configuring an Apache or Nginx server, which should be left as a manual process to avoid accidentally nuking an existing config.
