### ISSUE TITLE
What is the bundled file-sharing-patternfly.css.gz for, and where does it come from?

### ISSUE THREAD

**Issue by mattdm** [45Drives/cockpit-file-sharing#26]
Hi! I'm working on packaging this officially for Fedora. In general, we try to de-bundle things where we can. I noticed that there's a rather large `file-sharing-patternfly.css.gz` included that appears to be minimized css from several sources. This seems unusual compared to the other cockpit modules I've looked at... can this be simplified?

**Comment by joshuaboud** [comment]
Hi, this file was included to fix compatibility issues with Cockpit on Centos 7.

**Comment by mattdm** [comment]
Can you tell me what it contains and how it was generated? Running on Fedora Server 35, if I remove it, everything gets stuck up in a small viewport at the top of the panel, so it's still doing _something_ in that case. :)

**Comment by dawsondellavalle** [comment]
Hi there,

The decision was made with [Cockpit 221](https://cockpit-project.org/blog/cockpit-221.html) to remove `patternfly.css` from it's core utilities which was PatternFly 3 and a few other sources. `file-sharing-patternfly.css.gz` is a clone of what that file was in previous versions of cockpit. This was also done in the [cockpit-zfs-manager](https://github.com/45Drives/cockpit-zfs-manager) module that we currently maintain.
