### ISSUE TITLE
[request] provide basic instructions for installation on each distribution

### ISSUE THREAD

**Issue by brainchild0** [45Drives/cockpit-file-sharing#28]
The project apparently attempts to handle the different package managers of various distributions  by providing a single script that detects the distribution and perhaps other site details, and performs the desired administrative changes. However, this approach makes the applied changes opaque to the administrator. Many administrators prefer to know what configuration would be changed. Mostly, it would be easy to follow a few steps appropriate for a particular distribution, to configure the local package manager. Please consider providing such steps in the documentation, for use  as an alternative to running a script on the system.

**Comment by prascher** [comment]
And, I noticed a slight but important error in the Ubuntu instructions as they are, and that is the lack of `sudo` before `apt install`

**Comment by dawsondellavalle** [comment]
Hi all,

> The project apparently attempts to handle the different package managers of various distributions by providing a single script that detects the distribution and perhaps other site details, and performs the desired administrative changes. However, this approach makes the applied changes opaque to the administrator. Many administrators prefer to know what configuration would be changed. Mostly, it would be easy to follow a few steps appropriate for a particular distribution, to configure the local package manager. Please consider providing such steps in the documentation, for use as an alternative to running a script on the system.

We use a setup script to install our repositories onto our supported distributions. The setup script is very verbose in what it does and is completely open. The basis of what it does is check which distribution it is on, add the appropriate `.repo` or `.sources` file and then run an update on Debian or a clean all on RHEL-based distros. The script is available to view if you are concerned as to what it does. If you would rather not use our repositories, then you can install it with the appropriate `.rpm` or `.deb` package file available in the "Releases" section in this repository. If you have further concerns or questions, please let us know.

> And, I noticed a slight but important error in the Ubuntu instructions as they are, and that is the lack of `sudo` before `apt install`

We generally run these commands in an environment that `sudo` is not required so is not included in the documentation, and if it is required, that may need to be done on a case-by-case basis by our employees or end-users.

Kind regards,
Dawson Della Valle

**Comment by brainchild0** [comment]
> 
> We use a setup script to install our repositories onto our supported distributions. The setup script is very verbose in what it does and is completely open. The basis of what it does is check which distribution it is on, add the appropriate `.repo` or `.sources` file and then run an update on Debian or a clean all on RHEL-based distros. 

Detecting the distribution may be useful in a fully automated script. However, because administrators know the distribution of systems in their charge, a representation of the steps for manual use would not require detection of the distribution. It would simply require a distinct representation of the steps themselves for each distribution, as is already the case.



> The script is available to view if you are concerned as to what it does. 

Yes, but it is quite taxing to extract the relevant operations. I believe it would be valuable to include a transparent representation of the actions in the documentation.

> If you would rather not use our repositories, then you can install it with the appropriate `.rpm` or `.deb` package file available in the "Releases" section in this repository. If you have further concerns or questions, please let us know.

Yes, but again, it would be most helpful to show   the required items in a form that is easy for a human to read in the documentation.



> 
> > And, I noticed a slight but important error in the Ubuntu instructions as they are, and that is the lack of `sudo` before `apt install`
> 
> We generally run these commands in an environment that `sudo` is not required so is not included in the documentation, and if it is required, that may need to be done on a case-by-case basis by our employees or end-users.

It is customary to include the call to `sudo` in documentation, at least when representing commands on Ubuntu-like distributions. Such inclusion isolates the end user from the particular choices you have described for your own team.
