### ISSUE TITLE
[Feature Request] Ability to modify/create SMB shares with domain admin user

### ISSUE THREAD

**Issue by mmcphee** [45Drives/cockpit-file-sharing#30]
On servers joined to an active directory, it would be great for larger organizations if shares could be created by a domain admin user. As of right now, it appears it can only be done with root user and an admin would need to distribute root user credentials to anyone who would like to make a share in File Sharing tab.

sudo commands will change the user in the terminal - but the user on Houston/cockpit remains the same if we click on "Limited Access" and enter the password.

**Comment by joshuaboud** [comment]
Hey Mike, is this still an issue after the v3.x release? Everything the plugin runs should try to become root, and if becoming root is not possible, it will fall back to running the process as the user currently logged into Cockpit.

**Comment by joshuaboud** [comment]
Here's some information on Cockpit single sign on with a domain: https://cockpit-project.org/guide/latest/sso.html
