### ISSUE TITLE
Can't get Samba working

### ISSUE THREAD

**Issue by daaw-gees** [45Drives/cockpit-file-sharing#32]
Installed Ubuntu server on a Proxmox server as a VM, was able to get cockpit and filesharing installed with little issue. I'm now stuck on getting Samba to function properly. When I go to File Sharing > Samba I see this: 
![Annotation 2022-02-20 133343](https://user-images.githubusercontent.com/100091711/154859328-8b472d48-b7f5-47fe-98f6-ca68eb2aaa29.png)

So, I go onto the Ubuntu server so I can edit that file and apparently it's a sample: 
![Annotation 2022-02-20 135359](https://user-images.githubusercontent.com/100091711/154859386-1e652c76-2d65-4ada-8309-eab5ef74799c.png)

Could really use some assistance, googling "smb.conf is a sample," hasn't returned helpful results.

Thanks in advance,
-Nick

**Comment by joshuaboud** [comment]
Hi, you can just add `include = registry` right underneath where it says `[global]` in your existing smb.conf file

**Comment by daaw-gees** [comment]
I hope it isn't that simple, mine .conf just looks different from what it 'should' look like. That line at the top where it says 'sample' was giving me pause. I'll give that a try and report back.

**Comment by daaw-gees** [comment]
I didn't even put the proper indent and it still worked. Thanks for the quick response on a Sunday!

![Annotation 2022-02-20 163232](https://user-images.githubusercontent.com/100091711/154865167-0aea8dc2-4dfd-4d3f-8403-42a8460b9719.png)
![Annotation 2022-02-20 163052](https://user-images.githubusercontent.com/100091711/154865180-72dd36ba-824b-4699-a2b5-c3f1525a4c5e.png)
