### ISSUE TITLE
Support For home shares and VARIABLE SUBSTITUTIONS

### ISSUE THREAD

**Issue by joaodforce** [45Drives/cockpit-file-sharing#33]
I'm trying to make a home share for every user using variable substitutions, so basically using the path `/home/$u`

Which normally on smb would make the path be dynamic based on the logged user.

However this is not working here, the file sharing plugin instead actually created the `/home/$u` directory.

Is there any workaround for this?

<img width="760" alt="Screen Shot 2022-03-02 at 15 59 04" src="https://user-images.githubusercontent.com/9410916/156429802-e22d1dd5-76e9-4c8d-9871-2c27b4134bac.png">

**Comment by bkelly16** [comment]
fixed in release 2.4.5
