### ISSUE TITLE
Existing Shares

### ISSUE THREAD

**Issue by alexfornuto** [45Drives/cockpit-file-sharing#34]
Thanks for the plugin! I installed it after configuring Samba through `smb.conf` with the shares I needed. Those shares aren't showing up on Cockpit. Do I have to remove the share and recreate it through the GUI before it's visible?

**Comment by joshuaboud** [comment]
If it wouldn't take you too long, recreating them in the GUI is the easiest way to do it. Otherwise, see #27

**Comment by alexfornuto** [comment]
The shame of opening an issue when there's a previous one covering it is boundless. I will diminish, and go into the west.

**Comment by alexfornuto** [comment]
:facepalm:
