### ISSUE TITLE
[Feature Request] Ability to install via repo on Ubuntu 22.04

### ISSUE THREAD

**Issue by neononyx** [45Drives/cockpit-file-sharing#36]
Currentily following the instructions for "Ubuntu" does not work on 22.04.
Is there any plans to support this?

**Comment by nicoduj** [comment]
Hi, is it still an issue ? can't make it work on Ubuntu 22.04.1 LTS . Tried through "Ubuntu steps" or through downloading (latest version - 3.2.3-1) but all I get is an "oops" message in cockpit.

**Comment by joshuaboud** [comment]
Since this is a build infrastructure issue and not specifically for file sharing, I'll close this issue. We are currently working on updating our build process though to support Ubuntu 22.04 LTS, so it will be available once that's done.

**Comment by matthewpritchett** [comment]
@joshuaboud Just curious if there’s any update on supporting Ubuntu 22.04?
