### ISSUE TITLE
Not possible to use normal, nologin user as a Samba share user

### ISSUE THREAD

**Issue by kullervo610** [45Drives/cockpit-file-sharing#4]
To minimize attack footprint within my NAS as normal users but without shell, as nologin users (example of such user below).
pikachu:x:1009:1002:,,,:/home/pikachu:/usr/sbin/nologin

When looking into your code  
-> cockpit-file-sharing/file-sharing/samba-manager/samba-manager.js
-> function add_user_options()

you define nologin users as system users and filter them out. According my limited understanding this is not correct approach. Instead of using 'nologin' as criteria, please consider other means .e.g. do filtering based on UID ranges as system users are typically having UID <1000. You may look into Linux Standard Base (LSB) reserved ranges, implementations in different Linux distros as your reference for UID ranges for system users.

**Comment by sam55silver** [comment]
Hello, this issue has been noted and we plan to start work on this as soon as possible. Thank you for your help and you can expect an update in the near future.

**Comment by joshuaboud** [comment]
fixed with #6
