### ISSUE TITLE
where to setting the samba user password?

### ISSUE THREAD

**Issue by Omoinemie** [45Drives/cockpit-file-sharing#41]
`root@5005U-Linux:~# testparm
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed
Server role: ROLE_STANDALONE

Press enter to see a dump of your service definitions

# Global parameters
[global]
	log file = /var/log/samba/log.%m
	logging = file
	map to guest = Bad User
	max log size = 1000
	obey pam restrictions = Yes
	pam password change = Yes
	panic action = /usr/share/samba/panic-action %d
	passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
	passwd program = /usr/bin/passwd %u
	registry shares = Yes
	server role = standalone server
	unix password sync = Yes
	usershare allow guests = Yes
	idmap config * : backend = tdb

[文件]
	path = /mnt/文件
	read only = No
	valid users = @ilove ilove
`

![image](https://user-images.githubusercontent.com/31991443/180355473-3a86552d-4869-4602-809d-84686592d77c.png)
![image](https://user-images.githubusercontent.com/31991443/180355559-2b77e5e1-a3a7-4811-8da5-c1c3cffef9d5.png)

**Comment by Omoinemie** [comment]
root@5005U-Linux:~# smbpasswd -e ilove
Failed to find user ilove in passdb backend.
root@5005U-Linux:~# smbpasswd -n ilove
Failed to find entry for user ilove.

**Comment by joshuaboud** [comment]
Hi, I see that this is closed but will comment here anyway for other people who find this. Samba user management is now done through [cockpit-identities](https://github.com/45drives/cockpit-identities), and you can set the smbpasswd through the user editor in that plugin.
