### ISSUE TITLE
Feature Request: Ability to disable NFS tab

### ISSUE THREAD

**Issue by loganm** [45Drives/cockpit-file-sharing#5]
When I open File Shares, it defaults to the NFS tab and pops an error that I haven't setup NFS. Because this server lives in a Mac/windows network, I am only exposing SMB shares and haven't set up NFS for a reason.

It would be nice to have a configuration option to disable the NFS tab, or just change the default tab to SMB.

**Comment by sam55silver** [comment]
Hello loganm,
File-sharing saves the tab you were last on, so whenever you refresh the page you should still be on SMB shares if that was the last tab selected.
Let me know if this feature is working for you. If not I will have a look into it!
All the best,
Sam
