### ISSUE TITLE
Cannot log in to samba file sharing from MacOS

### ISSUE THREAD

**Issue by fvlasie** [45Drives/cockpit-file-sharing#54]
## Bug Info

**Describe the bug**
Trying to connect from MacOS gives me the error: The server may not exist or is unavailable at this time...

**To Reproduce**
1. Go to Finder>Network
2. Click on the server
3. Click "Connect as..."

**Expected behavior**
Successful connection.

**Screenshots**

<img width="264" alt="Screenshot 2022-08-27 at 12 09 33 PM" src="https://user-images.githubusercontent.com/33334298/187044791-63eab30f-73ae-403f-bfb8-ac844935414c.png">

## Client Side

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version Monterey 12.5.1

## Server Side
 - OS: Rocky 8
 - Cockpit Version: 264.1

**Additional context**
Used to work well before the most recent changes in the cockpit modules. Connecting with "Connect to server..." allows me to enter the username and password but always rejects it (shaking login window).

**Comment by fvlasie** [comment]
`[root@Treebeard /]# testparm
Load smb config files from /etc/samba/smb.conf
Unknown parameter encountered: "includes"
Unknown parameter encountered: "includes"
Loaded services file OK.
Weak crypto is allowed
`

**Comment by bailey-97** [comment]
Are you able to send over the output of "cat /etc/samba/smb.conf"? It looks like there could be an invalid option within looking at your testparm which could cause the share to not be accessible.

**Comment by fvlasie** [comment]
# this config was generated by cockpit-file-sharing after importing smb.conf
# original smb.conf location:
# '/etc/samba/smb.conf' -> '/etc/samba/smb.conf.bak'
[global]
        include = registry
security = user
passdb backend = tdbsam
include = /etc/cockpit/zfs/shares.conf
fruit:encoding = native
fruit:metadata = stream
fruit:zero_file_id = yes
fruit:nfs_aces = no
vfs objects = catia fruit streams_xattr
fruit:model = RackMac
admin users = bpaux, neo

**Comment by fvlasie** [comment]
Thank you for looking at this!
Apprently the config has switched to a registry based thingy which I do not know how to edit... :(
`/etc/cockpit/zfs/shares.conf` is empty.

**Comment by bailey-97** [comment]
Looks like there are no shares defined within your smb.conf file, was there any further output from "testparm" besides

Ah, just seen your reply. You can view and edit those shares with the "net conf" tool. 

net conf list will list the shares created by this.

Just out of curiousity were your shares created within the file sharing module? It's possible the /etc/cockpit/zfs/shares.conf is causes issues with your current conf, are you able to remove that line and recheck testparm?

**Comment by fvlasie** [comment]
Removing the `include = registry` entry eliminates the `Unknown parameter encountered: "includes"` error but I still cannot log in. In the old file-sharing cockpit module the samba passwords had to be set specifically for each user. Maybe because the registry is not working passwords are not bein transferred from the user accounts?

**Comment by fvlasie** [comment]
Yes my shares were created in the file sharing module. testparm did list the shares I just did not inluice them in the output I posted (trying to keep postings as short as possible).

Here is the output from 'net conf list':

```[root@Treebeard ~]# net conf list
Unknown parameter encountered: "includes"
[global]
        security = user
        passdb backend = tdbsam
        fruit:encoding = native
        fruit:metadata = stream
        fruit:zero_file_id = yes
        fruit:nfs_aces = no
        vfs objects = catia fruit streams_xattr
        fruit:model = RackMac
        admin users = bpaux, neo
        server string = TREEBEARD
        workgroup = WORKGROUP
        log level = 5
        include = /etc/cockpit/zfs/shares.conf

[Treebeard's Clearing]
        path = /Fangorn/Treebeard's Clearing
        guest ok = no
        comment = 
        valid users = 
        read only = no
        browseable = yes
        fruit:encoding = native
        fruit:metadata = stream
        fruit:zero_file_id = yes
        fruit:nfs_aces = no
        vfs objects = catia fruit streams_xattr

[Network Backup]
        path = /Fangorn/Network Backup
        guest ok = no
        comment = 
        valid users = 
        read only = no
        browseable = yes
        fruit:encoding = native
        fruit:metadata = stream
        fruit:zero_file_id = yes
        fruit:nfs_aces = no
        vfs objects = catia fruit streams_xattr

[test]
        path = /Fangorn/test
        guest ok = no
        comment = 
        valid users = 
        read only = no
        browseable = yes
        fruit:encoding = native
        fruit:metadata = stream
        fruit:zero_file_id = yes
        fruit:nfs_aces = no
        vfs objects = catia fruit streams_xattr
```

**Comment by bailey-97** [comment]
Based on your testparm output it seems that your share configurations are not being loaded by samba, so when clients go to access the server there are technically no shares for them to connect to. 

include = registry is the parameter that lets the module load/read the shares so I would recommend leaving that line within the configuration file, I suspect the other include = /etc/etc., is the line causing issues, if you are to remove that try once testparm once more and see if your share config then shows

**Comment by fvlasie** [comment]
OK, I accidentally ran `net conf drop` thinking it would dump all the info into std out....oh well!

I have quickly recreated a test share. The includes error is now gone but I still cannot log in. Same symptoms...

smb.conf:
```
[global]
        include = registry
```

testparm output:
```
[root@Treebeard ~]# testparm
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed

Server role: ROLE_STANDALONE

Press enter to see a dump of your service definitions

# Global parameters
[global]
        registry shares = Yes
        server string = Treebeard
        fruit:nfs_aces = no
        fruit:zero_file_id = yes
        fruit:metadata = stream
        fruit:encoding = native
        idmap config * : backend = tdb
        vfs objects = catia fruit streams_xattr


[Treebeard's Clearing]
        path = /Fangorn/test
        read only = No
```

**Comment by fvlasie** [comment]
net conf list output:
```
[root@Treebeard ~]# net conf list
[global]
        server string = Treebeard
        fruit:encoding = native
        fruit:metadata = stream
        fruit:zero_file_id = yes
        fruit:nfs_aces = no
        vfs objects = catia fruit streams_xattr

[Treebeard's Clearing]
        path = /Fangorn/test
        guest ok = no
        comment = 
        valid users = 
        read only = no
        browseable = yes
```

**Comment by fvlasie** [comment]
Just for the sake of testing I tried connecting as `guest` after allowing guest access...same symptoms so it probably isn't an auth issue...

**Comment by bailey-97** [comment]
Are you able to recreate the share as it was before/was that path accessible prior via smb? If it was then I agree it isn't an auth issue. I recall you mentioned the OS was rocky linux, did you reboot the server recently? if so just to confirm other things is the samba daemon running? 

systemctl status smb

 as well as is SELinux disabled? 
 
 getenforce 
 
 to check this,

if you're able to get the share config to be as similar as it was before when it did work that would also be a good step, I believe we're dealing more so with a samba issue here than something to do with the module itself

**Comment by fvlasie** [comment]
```
[root@Treebeard ~]# systemctl status smb
● smb.service - Samba SMB Daemon
   Loaded: loaded (/usr/lib/systemd/system/smb.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2022-08-27 13:22:25 PDT; 3min 46s ago
     Docs: man:smbd(8)
           man:samba(7)
           man:smb.conf(5)
 Main PID: 6310 (smbd)
   Status: "smbd: ready to serve connections..."
    Tasks: 4 (limit: 822920)
   Memory: 9.9M
   CGroup: /system.slice/smb.service
           ├─6310 /usr/sbin/smbd --foreground --no-process-group
           ├─6341 /usr/sbin/smbd --foreground --no-process-group
           ├─6342 /usr/sbin/smbd --foreground --no-process-group
           └─6343 /usr/libexec/samba/samba-bgqd --ready-signal-fd=50 --parent-watch-fd=14 --debuglevel=0 -F

Aug 27 13:22:24 Treebeard systemd[1]: Starting Samba SMB Daemon...
Aug 27 13:22:24 Treebeard smbd[6310]: [2022/08/27 13:22:24.998473,  0] ../../source3/smbd/server.c:1734(main)
Aug 27 13:22:24 Treebeard smbd[6310]:   smbd version 4.15.5 started.
Aug 27 13:22:24 Treebeard smbd[6310]:   Copyright Andrew Tridgell and the Samba Team 1992-2021
Aug 27 13:22:25 Treebeard systemd[1]: Started Samba SMB Daemon.
```

**Comment by fvlasie** [comment]
selinux is disabled
The share is configured the same way as it was before.

I really appreciate your help with this Bailey!

**Comment by bailey-97** [comment]
Hm, everything looks good there, when you're trying to map the share are you able to check the smb log file and see if there's anything in there? There should be some further info in there as to why the share isn't connecting

**Comment by fvlasie** [comment]
Aha! I just installed the old cockpit module out of desperation `yum install cockpit-samba-manager` _aaaannndd_ I can now log in with a user after setting the samba password! So it seems we are back to ab auth issue...

**Comment by bailey-97** [comment]
That is very interesting, is there any differences to testparm now that you have the old module installed?

**Comment by fvlasie** [comment]
Here is my testparm output:

```
[root@Treebeard ~]# testparm
Load smb config files from /etc/samba/smb.conf
Loaded services file OK.
Weak crypto is allowed

Server role: ROLE_STANDALONE

Press enter to see a dump of your service definitions

# Global parameters
[global]
	registry shares = Yes
	server string = Treebeard
	fruit:model = RackMac
	fruit:nfs_aces = no
	fruit:zero_file_id = yes
	fruit:metadata = stream
	fruit:encoding = native
	idmap config * : backend = tdb
	admin users = bpaux neo
	vfs objects = catia fruit streams_xattr


[Treebeard's Clearing]
	path = /Fangorn/Treebeard's Clearing
	read only = No


[Network Backup]
	path = /Fangorn/Network Backup
	read only = No
```

**Comment by bailey-97** [comment]
Ah, I missed where you mentioned you set a samba password on the user there! That smb.conf looks good, so it's possible that the password being set is why it's letting you in now.

We recently released a new module called cockpit-identities which allows configuration of users and groups, and also allows setting of smb passwords. Due to this, the function was then removed from the file sharing module

**Comment by fvlasie** [comment]
I see. I followed the instructions on this page for setting up Houston: https://knowledgebase.45drives.com/kb/kb450470-rocky-linux-houston-ui-installation/

It seems the identities module is not included in the list...

Thanks for your help Bailey!
