### ISSUE TITLE
Error installing cockpit-file-sharing in ubuntu 22.04 server

### ISSUE THREAD

**Issue by macvaz** [45Drives/cockpit-file-sharing#55]
## Bug Info

**Describe the bug**
I follow the generic installation instrucctions. When I execute make install, I get this error:

mac@minipc:~/cockpit-file-sharing_3.2.5_generic$ sudo make install
Installing file-sharing
Creating install directory
mkdir -p /usr/share/cockpit/file-sharing

Copying files
Done installing file-sharing

cp -af system_files/* /
cp: cannot stat 'system_files/*': No such file or directory
make: [Makefile:124: system-files-install] Error 1 (ignored)

**To Reproduce**
Just follow the generic installation instructions on a ubuntu 22.04 server.

**Expected behavior**
The installations finishes without error.

## Server Side
 - OS: Ubuntu 22.04 server
 - Cockpit Version: cockpit/jammy-backports,now 276-1~bpo22.04.1 all [instalado]

**Comment by joshuaboud** [comment]
Have you checked if the plugin is installed? This error is intentionally ignored by `make`, and is expected to be shown since this plugin doesn't have any system files to install.

**Comment by macvaz** [comment]
Hi @joshuaboud. Yes, the plugin is installed but not working properly as shown the the issue #56 

I just wanted to show the error messages to assess if something should be fixed.

Thanks a lot!

**Comment by joshuaboud** [comment]
Oh my bad, I did not realize both issues were opened by you. But yes all things look good here as far as installing goes.
