### ISSUE TITLE
icon fonts not loading (fontawesome.woff 404)

### ISSUE THREAD

**Issue by markhuang1212** [45Drives/cockpit-file-sharing#57]
## Bug Info

**Describe the bug**
Icon font is not loading on the page

**To Reproduce**
1. Install `cockpit` and `cockpit-file-sharing` on Fedora 36
2. Open cockpit, click on "file sharing" (firefox and chrome both have the problem)
3. Icon fonts are not loading ![Screenshot from 2022-09-12 09-50-45](https://user-images.githubusercontent.com/9739278/189561647-87f524f7-610f-49c5-b43e-1928146c9a4f.png)
4. In dev console, there is a 404 request for the font file ![Screenshot from 2022-09-12 09-51-20](https://user-images.githubusercontent.com/9739278/189561674-a4de01a8-0078-4fd7-b095-d2a377b5f789.png)

**Expected behavior**
The font should load

**Screenshots**
See above

**Console Output**
- Firefox:
  - `downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://server1.hmpg.dev/cockpit/$5e3a684201e1c869874b8329cc82bcace4898145a8ec126c6209130165e28f21/base1/fonts/fontawesome.woff?v=4.2.0`
- Chrome
  - `GET https://server1.hmpg.dev/cockpit/$5e3a684201e1c869874b8329cc82bcace4898145a8ec126c6209130165e28f21/base1/fonts/fontawesome.woff?v=4.2.0 net::ERR_ABORTED 404`
  - `file-sharing-patternfly.css:1`

## Client Side

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Browser: Firefox/Chrome
 - Version 104/105

## Server Side
 - OS: Fedora 36
 - Cockpit Version: 275

The problem is the same on Fedora37 beta and cockpit 276

Version of `cockpit-file-sharing`: 2.4.5 on both Fedora 36 and 37 beta

**Comment by joshuaboud** [comment]
Hi, file sharing version 2 is no longer maintained in favor of the overhauled version 3. This is another victim of cockpit-project/cockpit#17486, where Cockpit decided to remove Patternfly from their build process for Cockpit version 273 and up. File sharing v3 and up does not have this issue, however we do not maintain packaging for Fedora and they only have v2.4.5 packaged. You can try opening a bug blocking https://bugzilla.redhat.com/show_bug.cgi?id=2050752 for the Fedora team to resolve the issue. To fix the issue yourself, you can either downgrade Cockpit to 272 or lower, or install the latest cockpit-file-sharing following the generic installation instructions in the readme (and also install [cockpit-identities](https://github.com/45Drives/cockpit-identities/) for managing samba users). Another option that *might* work is downloading the attached 
zip file and extracting the missing assets to where they belong:
```bash
curl -LO https://github.com/45Drives/cockpit-file-sharing/files/9550363/base1.zip
sudo unzip base1.zip -d /usr/share/cockpit/base1
```
I am not able to test this though so let me know if it works.

**Comment by markhuang1212** [comment]
unzipping the file works on fedora

**Comment by 0ranki** [comment]
This issue is closed, but I wanted to add that when I stumbled on the same issue on Rocky Linux 8, just extracting the fonts/ directory from the above zip file fixed the issue. On Rocky 8, the fonts/ directory did not exist at all initially.

**Comment by godsyn** [comment]
Should anyone else on rocky have this issue, the commands are:
```
curl -LO https://github.com/45Drives/cockpit-file-sharing/files/9550363/base1.zip
unzip base1.zip fonts/fontawesome.woff fonts/glyphicons.woff fonts/patternfly.woff -d /usr/share/cockpit/base1/
```
