### ISSUE TITLE
broken error icon on fresh fedora-37 installed system -  cockpit-file-sharing-2.4.5-2.fc37.noarch

### ISSUE THREAD

**Issue by KKoukiou** [45Drives/cockpit-file-sharing#65]
![Screen Shot 2022-11-21 at 11 55 22](https://user-images.githubusercontent.com/14921356/203033305-86778523-3269-45a7-bd7b-11c3aaeeeaff.png)

**Comment by joshuaboud** [comment]
Hi, the version of File Sharing in Fedora is not maintained by us. Please see #57, which seems to be the same issue - and you can follow up on the Fedora bug tracker with the link provided in that issue thread.
