### ISSUE TITLE
e.g

### ISSUE THREAD

**Issue by podjons** [45Drives/cockpit-file-sharing#7]
e.g
RHEL 8  cockpit-file-sharing 2.30

![image](https://user-images.githubusercontent.com/24988506/130171404-47fe5ff6-78f4-45d0-b285-2a07b8c73363.png)

**Comment by sam55silver** [comment]
Hello, thanks for pointing out this bug. Turns out the loader was not clearing after it set the password due to a miss spelt function... Oops! This issue is fixed in v2.3.1. Case closed!
