### ISSUE TITLE
Write permission issue (Samba) Resolved

### ISSUE THREAD

**Issue by Manifoldme** [45Drives/cockpit-file-sharing#76]
May be I’m doing something wrong, but I tried everything I could,
still don’t have a permission to write, a read permission works.

Share directory permission – Mode: rwxrwxrwx (777)  Owner, Group, Other all boxes checked.

Samba password set.

Windows ACLs – enabled
vfs objects = acl_xattr
map acl inherit = yes
acl_xattr:ignore system acls = yes

Guest OK – enabled
Browseable – enabled

Any suggestion would be much appreciated.

**Comment by vinceingithub** [comment]
How did you fix this? I'm having the same issue. I've tried everything in every thread on samba issues but nothing will work.
