### ISSUE TITLE
Edit users/groups of the Samba share after creation

### ISSUE THREAD

**Issue by megavenik** [45Drives/cockpit-file-sharing#95]
Hello!

I've created first share, decided to make it available to anonymous users and discovered, that it's a read-only share. So I've opened the share parameters once again to add some users to it, but there was nothing:

![image](https://github.com/45Drives/cockpit-file-sharing/assets/815281/4c7ef895-956c-43a0-bc3b-b0802bdf5227)

![image](https://github.com/45Drives/cockpit-file-sharing/assets/815281/db0fcbe1-0008-49a2-8000-3e41751d011a)

What am I doing wrong and how do I edit users/groups on the existing share?

Thanks!

**Comment by megavenik** [comment]
ooohh, looks like it hides when selecting some of the "ACLs" options!

**Comment by rhclayto** [comment]
I have this behavior even on trying to create a new share, & I haven't done anything with the settings for Windows ACLs.
